api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.APIRootView.as_view(), name='api-root'),
    path('categories/', views.CategoryListView.as_view(), name='category_list_api'),
    path('categories/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail_api'),
    path('categories/<int:category_id>/questions/', views.QuestionListView.as_view(), name='question_list'),
]

quiz_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('core.urls')),
    path('', include('quizzes.urls')),
    path('api/v1/', include('api.urls')),
]

quizzes/models.py
from django.db import models
from django.contrib.auth.models import User
import random


class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.name)

class Question(models.Model):
    QUESTION_TYPE_CHOICES = [
        ('multiple', 'Multiple Choice'),
        ('boolean', 'True/False'),
    ]

    DIFFICULTY_CHOICES = [
        ('easy', 'Easy'),
        ('medium', 'Medium'),
        ('hard', 'Hard'),
    ]

    question_type = models.CharField(max_length=10, choices=QUESTION_TYPE_CHOICES)
    difficulty = models.CharField(max_length=10, choices=DIFFICULTY_CHOICES)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    question_text = models.TextField()
    correct_answer = models.CharField(max_length=255)
    incorrect_answers = models.JSONField()
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    is_approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.question_text)

    def get_all_answers(self):
        # Combine correct answer with incorrect answers
        answers = self.incorrect_answers + [self.correct_answer]
        # Shuffle to randomize the position of the correct answer
        random.shuffle(answers)
        return answers

    @property
    def get_randomized_choices(self):
        """generates a list of answer choices in random order.

        Returns:
            list: A list of answer choices in random order.
        """
        choices = [choice for choice in self.incorrect_answers]
        choices.append(str(self.correct_answer))
        random.shuffle(choices)
        print(choices)
        return choices

class Quiz(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    questions = models.ManyToManyField(Question)
    time_limit = models.IntegerField(default=0)
    score = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)


class UserResult(models.Model):
    """Represents a user's result for a specific quiz.

    Attributes:
        user (User): The user who took the quiz.
        quiz (Quiz): The quiz that was taken.
        score (int): The user's score for the quiz.
        completion_time (timedelta): The time it took for the user to
        complete the quiz.
    """
    user = models.ForeignKey(
        User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    score = models.IntegerField()
    # completion_time = models.DurationField()

    def __str__(self):
        return f"{self.user.username} - " \
               f"{self.quiz.id} - {self.score}"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <title>Quiz Wiz</title>

    <!-- Bootstrap core CSS -->
    <link
      href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %} "
      rel="stylesheet"
    />

    <!-- Favicons -->
    <link href="{% static 'images/quiz.png' %}" rel="icon" />

    <link href="{% static 'css/main.css' %} " rel="stylesheet" />

    {% block custom_styling %}

    {% endblock custom_styling %}
  </head>
  <body class="color">
    <main class="color">
      <!-- NEW NAVBAR -->
      <nav class="navbar navbar-dark navbar-expand-lg px-lg-5 mb-2 border-bottom border-light">
        <div class="container-fluid d-flex align-items-baseline">
          <a class="navbar-brand d-flex align-items-center " href="{% url 'home' %}">
          <img
            src="{% static 'images/quiz.png' %}"
            alt="Logo"
            width="30"
            height="24"
            class=""
          />
          <span class="logo">Quiz Wiz</span>
          </a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto mb-2 mb-lg-0">


              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                Quizzes
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'select_quiz' %}">Take Quiz</a></li>
                  <li><a class="dropdown-item" href="{% url 'category_list' %}">Categories</a></li>
                </ul>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'api_info' %}">API</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
              </li>
            </ul>
            <div class="d-flex me-5 pe-5">
              {% if user.is_authenticated %}
              <ul class="navbar-nav">
                <li class="nav-item dropdown">
                  <a
                    class="nav-link dropdown-toggle"
                    href="#"
                    role="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                  {{ user.username }}
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'user_dashboard' %}">User Dashboard</a></li>
                    {% if user.is_superuser %}
                    <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin Dashboard</a></li>
                    {% endif %}
                    <li><hr class="dropdown-divider" /></li>
                    <li>
                      <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    </li>
                  </ul>
                </li>
              </ul>
              {% else %}
              <a href="{% url 'login' %}" class="btn text-white btn-outline-primary me-3">Login</a>
              <a href="{% url 'register' %}" class="btn btn-primary">Sign-up</a>
            </div>
            {% endif %}
          </div>
        </div>
      </nav>
      <!-- /NEW NAVBAR -->
      <div class="container">
        <div id="global_container">
          {% block content %}
          {% endblock content %}
        </div>

        <footer class="pt-3 mt-4 text-white text-center border-top">
          Quiz Wiz &copy; 2024
        </footer>
      </div>
    </main>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>